version: '3.8'

services:
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_LOWER}/jgec-frontend:latest
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_LOWER}/jgec-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./Jgec_Alumni_Backend/public:/app/public

  admin:
    image: ghcr.io/${GITHUB_REPOSITORY_LOWER}/jgec-admin:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
