interface ScholarshipDetail {
	_id: string;
	title: string;
	subtitle: string;
	description: string;

	providerName: string;
	providerDepartment: string;
	providerAdmissionYear: number;
	providerPassingYear: number;
	providerDetails: string;
	imageUrl: string;

	firstSem: boolean;
	secondSem: boolean;
	thirdSem: boolean;
	fourthSem: boolean;
	fifthSem: boolean;

	whocanApply: string;
	AgeCriteria: string;
	amountdetails: string;
	whentoApply: string;
	createdAt: string;
	updatedAt: string;
	__v: number;
}

export const ScholarshipDetails: ScholarshipDetail[] = [
	{
        "_id": "6791ca47b0fd27a34b1650d2",
        "title": "CONFIDENT & PROFESSIONAL PERSONALITY SCHOLARSHIP is sponsored by Mr. Bibhas Bhowmik (JGEC, Civil 1981-85)",
        "subtitle": "For 3rd year civil engineering students only",
        "description": "To promote this noble initiative of Alumni Association among JGECian, Mr. BIbhas Bhowmik ( Graduated from JGEC, CE dept in 1985) has started a scholarship programme in the year 2013 for 3 rd year Civil Engineering students. Purpose of the alumni scholarship programme is to help meritorious students who need some financial assistance to achieve their career goal.",
        "providerName": "Bibhas Bhowmik",
        "providerDepartment": "Civil",
        "providerAdmissionYear": 1981,
        "providerPassingYear": 1985,
        "providerDetails": "Bibhas Bhowmik Graduated in 1985 and post graduated from IIT- Delhi in 1992 with Applied Mechanics and got affiliated membership From Institute of Structural Engineers (UK) in 1996. He worked with Premier Engineering Consultants in India, namely TATA- MAN, DCPL, C E S and EIL till 1995 and then worked with International Contracting and Consulting firms @ UAE and UK, Originated from UK and Netherland. Since past 11 years he is working with National Oil & Gas producing & operating Government organisations in Qatar and UAE as key Technical team member in their Major Projects with Billion + USD worth EPC value. Simultaneously he worked as part time Lecturer for Undergraduate Civil Engineering Degree Curriculum ,Conducted from British Centre of Applied Studies affiliated UK universities off campus units and taught Contracts Management , Structural Mechanics etc. Understanding critical structural scheme and facing challenging projects are Bibhas Bhowmik’s passion.",
        "imageUrl": "/uploads/scholarship/Bibhas-Bhowmik-1737607751252-WhatsApp Image 2025-01-23 at 08.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": false,
        "whocanApply": "3rd year Civil Engineering students are eligible to apply",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "INR 15,000 to one 3rd year civil engineering student. Additional one extra scholarship of same amount may be provided to second best selected student depending on candidate's profile and fund situation.",
        "whentoApply": "Within 15 February Every year",
        "createdAt": "2025-01-23T04:49:11.262Z",
        "updatedAt": "2025-01-23T04:49:11.262Z",
        "__v": 0
    },
    {
        "_id": "6791d36e50171589fdd8d4fd",
        "title": "Indu Bhushan Memorial Scholarship",
        "subtitle": "For 3rd year civil engineering students only",
        "description": "Merit is inherent and cannot be suppressed or dominated for long by various circumstances which are in one way or the other parts of our life. To support a merit to bloom at a proper time, resources required may not be available readily. For a meritorious aspiring student, money at times poses as an obstacle in his or her path to pursue studies. At such juncture, a scholarship helps the scholar to a great extent.Many a student of high merit comes from a family with weak financial capacity and in the process of studying civil engineering at Jalpaiguri Govt. Engineering College (JGEC), dearth of funds restricts them to meet the basic expenses. ",
        "providerName": "Indu Bhushan Bhattacharya",
        "providerDepartment": "Civil",
        "providerAdmissionYear": 1985,
        "providerPassingYear": 1989,
        "providerDetails": "Indu Bhushan Bhattacharya was born in 1923 to an economically poor family and struggled hard to pursue his studies. For want of money to pay his school fees, his name was struck off the roll a couple of months before the matriculation examination. One of his neighbours stood to the occasion to pay off the dues and Indu Bhushan passed the examination in first division. Later, in pursuing graduation, he faced the same constraints and joined a job to become the sole bread earner of the family instead of attending the college. Still, his zeal for further persuasion of studies made him to enrol in a night college in Calcutta and he stood second in B Com from the Calcutta University. His dream of further studies however ended here due to family commitments. He continued with the service in the Income Tax Department and rose to the level of IRS Officer with his dead honesty and hard work throughout his entire career. He also taught Income Tax Officers for about two years before his superannuation in 1982.Ullas Bhattacharya is the youngest son of Indu Bhushan and pursued Civil Engineering from JGEC from 1985 to 1989 and topped the class in 1989. National Scholarship helped him a lot to meet the expenses as his father’s pension was not at all a handsome figure as nowadays. Ullas has followed the footstep of his father in social works, activities, helping the meritorious students in need and move ahead with his head high by virtue of dead honesty & sincerity. It is ",
        "imageUrl": "/uploads/scholarship/Indu-Bhushan Bhattacharya-1737610094879-Picture1.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": false,
        "whocanApply": "with at least 70% marks in aggregate and 75% in Strength of Materials",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Indu Bhushan Memorial Scholarship of Rs.30000 (Rupees thirty thousand only) is awarded to an economically weak civil engineering student promoted to 3rd year with at least 70% marks in aggregate and 75% in Strength of Materials.",
        "whentoApply": "Within 15 February Every year",
        "createdAt": "2025-01-23T05:28:14.909Z",
        "updatedAt": "2025-01-23T05:28:14.909Z",
        "__v": 0
    },
    {
        "_id": "6791dcd8eed0e6105e88f5e4",
        "title": "Late Anima Sen Memorial Scholarship",
        "subtitle": "Any JGEC girl student from any discipline, 2nd Year onwards",
        "description": "This financial assistance is a humble attempt to pave the way for the smooth academic endeavor of a girl student who is in need of a little support on her journey towards fulfilment of a dream. The little support is a blessing from my mother. I am just a catalyzer for this happy moment. The objective of this scholarship is to empower and support a girl student confronting severe economic constraints in completing her under graduate education. The recipient of the scholarship must use the amount only for academic purpose during her stay at Jalpaiguri Govt. Engineering College for pursuing her studies. ",
        "providerName": "Dr. Nabanita Sen",
        "providerDepartment": "N/A",
        "providerAdmissionYear": 0,
        "providerPassingYear": 0,
        "providerDetails": "Dr. Nabanita Sen, daughter of Late Anima Sen, humbly offers this financial support to a girl student enrolled in an engineering course for her bright future. She hopes that the recipient will in turn stretch out her helping hands to other deprived and vulnerable girl students in need of assistance when she is herself financially independent, self-sufficient and in a position to do so.",
        "imageUrl": "/uploads/scholarship/Dr.-Nabanita Sen-1737612504684-istockphoto-1332100919-612x612.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": false,
        "fourthSem": false,
        "fifthSem": false,
        "whocanApply": "Any JGEC girl student from any discipline, 2nd Year onwards,(1) who has consistent good result, (2) has record of regular attendance in classes, (3) actively participates in all programs of the college, (4) keeps herself busy with outreach programs undertaken by the institution, and needs financial assistance to continue the engineering course. The candidate is to satisfy the interviewerin respect of the aforesaid points.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "An amount of Rs. 25,000/- (Twenty-five thousand only) to any girl student fulfilling the above-mentioned criteria.",
        "whentoApply": "Between date of notification of scholarship and cut off dates for application receipt.",
        "createdAt": "2025-01-23T06:08:24.688Z",
        "updatedAt": "2025-01-23T06:08:24.688Z",
        "__v": 0
    },
    {
        "_id": "6791df6aeed0e6105e88f5e6",
        "title": "LATE MRINAL KANTI SANYAL GOOD WILL  SCHOLARSHIP",
        "subtitle": "For Mechanical engineering students only",
        "description": "When it comes to paying back to college, scholarships are the best form of financial aid. In order to inspire and support the students who encounter the problems such as inability to cope with the high standards of studying as well as difficulty in paying recurring expenses such as tuition fees, hostel & mess charges and accessing basic study needs, I have decided to introduce and continue scholarships to the financially challenged, academically sounds and socially involved students. This is an honest & sincere effort and a token pay back to my college",
        "providerName": "Pinaki Ranjan Sanyal",
        "providerDepartment": "Mechanical",
        "providerAdmissionYear": 1987,
        "providerPassingYear": 1991,
        "providerDetails": "Pinaki Ranjan Sanyal (1987 Mechanical). The name of the scholarship will be  LATE MRINAL KANTI SANYAL GOOD WILL  SCHOLARSHIP",
        "imageUrl": "/uploads/scholarship/Pinaki-Ranjan Sanyal-1737613162557-Picture2.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": true,
        "whocanApply": "Any JGEC student from Mechanical Discipline, 1st Semester onwards, who is performing well and needs economic aid to continue their engineering course.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Rs. 11,000/- each to 1 undergraduate engineering students of JGEC.",
        "whentoApply": "Between date of notification of scholarship and cut off dates for application receipt.",
        "createdAt": "2025-01-23T06:19:22.570Z",
        "updatedAt": "2025-01-23T06:19:22.570Z",
        "__v": 0
    },
    {
        "_id": "6791e218eed0e6105e88f5e8",
        "title": "ME23 by Mechanical Engineering ",
        "subtitle": "For 2nd and 3rd year Mechanical engineering students only",
        "description": "When it comes to paying back to college, scholarships are the best form of financial aid. In order to inspire and support the students who encounter the problems such as inability to cope with the high standards of studying as well as difficulty in paying recurring expenses such as tuition fees, hostel & mess charges and accessing basic study needs, we the Jolites of 2023 batch of Mechanical Engineering decided to introduce and continue scholarships to the financially challenged, academically sound and socially involved students of Mechanical Engineering Department. This is an honest & sincere effort and a token pay back to our place of graduation where we have spent our precious four years of life.",
        "providerName": "Alumnus of 2023 Mechanical Engineering Batch",
        "providerDepartment": "Mechanical",
        "providerAdmissionYear": 2019,
        "providerPassingYear": 2023,
        "providerDetails": "We, the jolites of 2023 batch Mechanical Engineering have united for the ME23 scholarship.This Scholarship is a humble effort to encourage our future generation to excel and a small gesture to help ease some financial burden for our current students and help them achieve their career aspirations.With Best Regards,Alumnus of 2023 batch of Mechanical Engineering",
        "imageUrl": "/uploads/scholarship/Alumnus-of 2023 Mechanical Engineering Batch-1737613848666-Mechanical23.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": false,
        "whocanApply": "Any JGEC student of Mechanical Engineering department, studying in 2nd and 3rd year, who is performing well and needs economic aid to continue their engineering course.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Rs. 10,000/- each to 3 (2 no. of 3rd year + 1 no. of 2nd year) undergraduate engineering students of JGEC",
        "whentoApply": "Between date of notification of scholarship and cut off dates for application receipt.",
        "createdAt": "2025-01-23T06:30:48.692Z",
        "updatedAt": "2025-01-23T06:30:48.692Z",
        "__v": 0
    },
    {
        "_id": "6791e656eed0e6105e88f5ed",
        "title": "LATE AJIT KUMAR GHOSH MEMORIAL SCHOLARSHIP",
        "subtitle": "For one 2nd Year Engineering Students from any Department",
        "description": "This scholarship is recognition to the student who as the top performer of Joint Entrance Examination in the state (WBJEEE) has joined and continued at Jalpaiguri Government Engineering College for more than one year. The student need not apply, here the Alumni association in communication with the college authorities shall collect the name and contact details of top three WBJEE rank holders on behalf of the Scholarship sponsor. The sponsor on his discretion shall select the suitable candidate and award the scholarship. Scholarship shall be offered usually during the annual Alumni meet every year in the month of August",
        "providerName": "Partha Pratim Ghosh",
        "providerDepartment": "Mechanical",
        "providerAdmissionYear": 1991,
        "providerPassingYear": 1995,
        "providerDetails": "Partha Pratim Ghosh entered JGEC in the year 1987 as a lowest rank holder of WBJEE of all the students who took admission in JGEC in that year and at that time there was only three branches, he took admission in Mechanical Engineering and by virtue of WBJEE rank become “MECH 1”. In the college he served as Magazine Secretary. After graduation from JGEC in 1991 and PGDBM from IISWBM, he served various organizations at different capacity. Besides his profession, he is also a writer in Bengali Language. This scholarship is in the name his father Late Ajit Kumar Ghosh, who was a victim of the trails of partition in 1947 when he has to leave his ancestral house with many people which is in the present Bangladesh and fought the battle on his own to become successful in his field. He has sacrificed his entire life for the comforts of the people, as a result many people has become what they are now. He is the real star, real fighter whose contribution to the people cannot be described in few words and he lives in their heart for ever.",
        "imageUrl": "/uploads/scholarship/Partha-Pratim Ghosh-1737614934347-LATE AJIT KUMAR GHOSH MEMORIAL SCHOLARSHIP.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": false,
        "fourthSem": false,
        "fifthSem": false,
        "whocanApply": "For one 2nd Year Engineering Students from any Department",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "INR 5000/= one time only every year. ",
        "whentoApply": "Between date of notification of scholarship and cut off dates for application receipt.",
        "createdAt": "2025-01-23T06:48:54.361Z",
        "updatedAt": "2025-01-23T06:48:54.361Z",
        "__v": 0
    },
    {
        "_id": "6791e80deed0e6105e88f5ef",
        "title": "UNISON – 2007 Scholarship",
        "subtitle": "For any student from any department & batch",
        "description": "An unconditional friendship, without expectations of return, is the highest form of compassion & love. Lucky are those few, like us, who unknowingly earned numerous unconditional friends, during our own 4 year epic saga of this great institution, back in 2003 – 2007. Most of our grown-up daily lives revolve around eventual interests, involving provisional friends, colleagues & strangers. All they question is how useful am I, for their own interests; apart from our beloved ones. By fighting this cruel professional world with inclined interests, gradually, we lose our innocence. This innocence is that X factor, which used to award us such unconditional friends, at this utopian world of Jolu, somewhere down the evergreen alleys of our memory lanes. For every passing-out grown-up Joluites, this unforgiving Real World is waiting to greet them, equipped with never ending competitions, demands & targets. We work hard, here in this Real World, for the rest of our lives, without encountering unconditional friends, anymore. Only scarce, tiny & reasonable euphoric moments remain for us, to hold on to & to move on to, leaving the ashes of Jolu at the bottom of our hearts. As time passes, little by little, we forget the very key learning from our hostel heydays - I am happy, without any reason, just because it’s natural state of my mind. The sole cause of this scholarship is to honor the virtue of unconditional friendship & to encourage our junior counterparts towards this very culture that makes us Joluites unique, by every means of humanitarian ethics & nobility. For the recipients of this scholarship & his/her mates, all we can say is - Good Luck. Please don’t forget, you carry a legacy of true friends. It will help you to sail through the ocean of Life. As a token gratitude for your effort, we would like to introduce UNISON-2007 Scholarship, to commemorate our beloved classmate Partha.",
        "providerName": "UNISON – 2007 (A group of 2007 Pass-outs, friends of Late Partha Pratim Mondal)",
        "providerDepartment": "ECE",
        "providerAdmissionYear": 2003,
        "providerPassingYear": 2007,
        "providerDetails": "We met at the unripe stage of adolescence, when love had all power, more than anything else. It flourished the artistic talents hidden deep within our abilities, without any hindrance. Art is the extreme form of love & it is not biased by interests. Partha was such an artist. Now-a-days, we see a lot of decoration arts like Rangoli & Kolam sweeping digital media, duly corrected by all means of Artificial Intelligence. Back in early 2000s, we were spellbound by the sheer brilliance of Partha & his exceptional art of ALPANA, purely produced by artistic skills of Natural Intelligence. His elated sense of perfection in mirroring shapes & repeating patterns, sketched gigantic & extravagant Alpana, all over the auditorium & hostel common rooms, during different cultural festivals which used to mesmerize us. Isn’t Engineering all about reading patterns? Read the pattern, crack the code. We used to get lost in these mosaics & mazes, on his Alpanas, without any reason, with nothing but awestricken appreciation. He was from ECE department. After graduation, he was working at Vodafone. In 2014, during a tower visit near Pune, a fatal road accident caused melancholic demise of our dear friend. It took him away from us and left only heart melting memories of him. We had an artist amongst us & we lose him just like that, within blink of an eye. He is the first person of our 2003-2007 Batch to depart from this temporary world. What an untimely & unfortunate end of a valuable mind; a mind with capability to think & produce flamboyant Alapans at ease. We all will meet someday, at the Gates of the after-world, where Partha will be waiting for us with his upgraded UHD Alpanas, to welcome us all with unconditional love, an art of lifestyle that we all learnt back in Jolu during a really unrealistic time.",
        "imageUrl": "/uploads/scholarship/UNISON-– 2007 (A group of 2007 Pass-outs, friends of Late Partha Pratim Mondal)-1737615373527-Unison-2007.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": true,
        "whocanApply": "Any student from any department & batch",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Two scholarships will be provided (Rs.12,500/- each)",
        "whentoApply": "Between date of notification of scholarship and cut off dates for application receipt.",
        "createdAt": "2025-01-23T06:56:13.530Z",
        "updatedAt": "2025-01-23T06:56:13.530Z",
        "__v": 0
    },
    {
        "_id": "6791e9f6eed0e6105e88f5f1",
        "title": "Scholarship from Batch 2002",
        "subtitle": "For - 3rd Semester UG students of Civil, Electrical and Mechanical Engg. Departments",
        "description": "Supporting student with scholarships is a very humble attempt at paying back to one’s beloved alma mater. Though, it is never possible to return in the same measure as we had received from this great institute, still, it will give us immense pleasure if this small effort benefits someone, even to the smallest extent possible. With this in mind, allow us, the Joluites of Batch 2002, to introduce the ‘Scholarship from Batch 2002’ to inspire and support some academically sound and socially involved students in the Civil, Electrical and Mechanical Engineering departments facing hardship in meeting recurring expenses such as tuition fees, hostel and mess charges and other basic academic expenses.",
        "providerName": "The Alumni of Batch 2002",
        "providerDepartment": "N/A",
        "providerAdmissionYear": 1998,
        "providerPassingYear": 2002,
        "providerDetails": "JGEC 2002 Graduating Batch ",
        "imageUrl": "/uploads/scholarship/The-Alumni of Batch 2002-1737615862969-istockphoto-1332100919-612x612.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": false,
        "fourthSem": false,
        "fifthSem": false,
        "whocanApply": "3rd Semester UG students of Civil, Electrical and Mechanical Engg. Departments who need support to continue their degree",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "One each from 3rd Semester of the UG program of Civil, Electrical and Mechanical Engg. Departments in the current year. Rs. 15000/- (Fifteen Thousand only) per year per candidate",
        "whentoApply": "Between date of notification of scholarship and cut off dates for application receipt.",
        "createdAt": "2025-01-23T07:04:22.971Z",
        "updatedAt": "2025-01-23T07:04:22.971Z",
        "__v": 0
    },
    {
        "_id": "6791eaf8eed0e6105e88f5f3",
        "title": "Maayer Ashirbad",
        "subtitle": "For any student from 2nd semester onwards.",
        "description": "The aim of this financial support is to lift students out of poverty in our community by empowering them through education and giving them the opportunity to build for themselves the life they deserve. By this I could benefit their parents, siblings and communities as a whole through shared knowledge and education, thus increasing the happiness of many, including that of their benefactors. This sponsorship will enhance the human dignity of those in need and provides new life. It offers a rich experience for you, your family and friends. Maayer Ashirbad is meant to get the blessings of a mother to attain your goal by overcoming theobstacles in your front.",
        "providerName": "Amitava Sil",
        "providerDepartment": "N/A",
        "providerAdmissionYear": 2000,
        "providerPassingYear": 2004,
        "providerDetails": "Shri AmitavaSil (2000) elder son of Smt. Swarnamayee Sil is humbly dedicated to offer financial support to engineering students to build a bight career.",
        "imageUrl": "/uploads/scholarship/Amitava-Sil-1737616120135-istockphoto-1332100919-612x612.jpg",
        "firstSem": true,
        "secondSem": false,
        "thirdSem": false,
        "fourthSem": false,
        "fifthSem": false,
        "whocanApply": "Any JGEC student from any discipline, 2nd Semester onwards who is performing well and needs economic aid to continue their engineering course.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Rs. 20,000/- each to 2 undergraduate engineering students of JGEC.",
        "whentoApply": "Between date of notification of scholarship and cut off dates for application receipt.",
        "createdAt": "2025-01-23T07:08:40.142Z",
        "updatedAt": "2025-01-23T07:08:40.142Z",
        "__v": 0
    },
    {
        "_id": "6791ec24eed0e6105e88f5f5",
        "title": "GHOSAL FAMILY SCHOLARSHIP ",
        "subtitle": "For first year Engineering (Computer Science Stream Student only ) Freshers.",
        "description": "GFS Scheme is established to help JGEC student who have faced hardship and adversity and wish to complete an undergraduate education. The purpose of this scholarship is to support financially challenged promising engineering student who wish to complete the undergraduate education.  Theme behind this scholarship is to portray the message You are not alone in your struggle. Documents to Provide  : ----  Applicants will provide their Secondary and Higher Secondary and Engineering Entrance examination score /  rank details along with family income certificate verified   by their School Principal official seal with address and contact details .   ",
        "providerName": "Mrs. Shyamoli Ghosal and Partha S. Ghosal",
        "providerDepartment": "Civil",
        "providerAdmissionYear": 1996,
        "providerPassingYear": 1970,
        "providerDetails": "Mrs. Shyamoli Ghosal and Partha S. Ghosal (JGEC, Civil 1970).",
        "imageUrl": "/uploads/scholarship/Mrs.-Shyamoli Ghosal and Partha S. Ghosal-1737616420119-istockphoto-1332100919-612x612.jpg",
        "firstSem": true,
        "secondSem": false,
        "thirdSem": false,
        "fourthSem": false,
        "fifthSem": false,
        "whocanApply": "First year Engineering (Computer Science Stream Student only ) Freshers in campus always . ",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Amount to cover Tuition, room and boarding – lodging , books, etc. ( Amount might vary based on market price index and to be shall be finalized determined by Alumni Association the scholarship committee). Maximum amount limited to INR 70,000 to one student . If no needy student is identified within above mentioned Engineering stream students then the scholarship shall be open to other Engineering stream students as well amount will be carried over to the next academic year.",
        "whentoApply": "Between date of notification of scholarship and cut off dates for application receipt.",
        "createdAt": "2025-01-23T07:13:40.123Z",
        "updatedAt": "2025-01-23T07:13:40.123Z",
        "__v": 0
    },
    {
        "_id": "6791ed7aeed0e6105e88f5f7",
        "title": "Merit Scholarship",
        "subtitle": "Any JGEC student from any discipline, 3rd Semester onwards",
        "description": "With this scholarship, intention is to help 1 student who have financial hardships in completing their undergraduate courses. The recipients of this scholarship will be able to use this amount to pay for education and other expenses that they would incur in their stay while studying at JGEC.",
        "providerName": "JGEC Alumni of 1995",
        "providerDepartment": "N/A",
        "providerAdmissionYear": 1991,
        "providerPassingYear": 1995,
        "providerDetails": "JGEC Alumni of 1995 (Initiated from 2021)",
        "imageUrl": "/uploads/scholarship/JGEC-Alumni of 1995-1737616762779-istockphoto-1332100919-612x612.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": true,
        "whocanApply": "Any JGEC student from any discipline, 3rd Semester onwards, who is performing well and needs monetary assistance to continue their engineering course.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Rs. 30,000 to 1 undergraduate engineering students of JGEC",
        "whentoApply": "Between date of notification of scholarship and cut off dates for application receipt.",
        "createdAt": "2025-01-23T07:19:22.782Z",
        "updatedAt": "2025-01-23T07:19:22.782Z",
        "__v": 0
    },
    {
        "_id": "6791eea7eed0e6105e88f5f9",
        "title": "The Emerging Engineer Scholarship",
        "subtitle": "For JGEC student of any discipline",
        "description": "The Emerging Engineer scholarship is introduced to help the meritorious JGEC student who is in need of a small financial help during the year to complete his/her undergraduate education. This is extended as a token of love and support from an old alumnus of JGEC.",
        "providerName": "Bireschandra Bhaumik",
        "providerDepartment": "Mechanical",
        "providerAdmissionYear": 1964,
        "providerPassingYear": 1968,
        "providerDetails": "I remember my JGEC days back in the 1960s. This engineering college lacked full-fledged infrastructure during those formative years. The inadequacy coupled with the then industrial, economic and political scenario of the state of West Bengal made the students devise their own ways to mitigate their own difficulties. Quite a good number of the students of those days could prominently establish themselves in the real world later. The situation is much better today. However, it is believed that small financial help from here and there would be of great use to the needy and meritorious students of JGEC for leading themselves to the wide open world. With this idea in mind this small gesture is made toward providing an incremental help to my young JGEC friends.",
        "imageUrl": "/uploads/scholarship/Bireschandra-Bhaumik-1737617063014-Bireschandra Bhaumik.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": true,
        "whocanApply": "JGEC student from any discipline, who is performing well and is in need of monetary assistance to continue his/her engineering curriculum.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Rs. 12,000 to one undergraduate engineering student of JGEC for the year.",
        "whentoApply": "Between date of notification of scholarship and cut off dates for application receipt.",
        "createdAt": "2025-01-23T07:24:23.016Z",
        "updatedAt": "2025-01-23T07:24:23.016Z",
        "__v": 0
    },
    {
        "_id": "6791f0afeed0e6105e88f5fb",
        "title": "DEBDAS MUKHERJEE MEMORIAL SCHOLARSHIP",
        "subtitle": "For Any Engineering Students from (2nd year onwards) Of JGEC",
        "description": "Interested students for various scholarship schemes shall note that these schemes will remain effective at least for 5 years as minimum from it's year of inception. However if it gets discontinued within above mentioned period due to any emergency reason from Sponsor's side, then Alumni Association shall not remain responsible for that act of discontinuity. Students with documented financial requirement are now being offered the opportunity to apply for scholarships which can be helpful for them to meet some educational needs.",
        "providerName": "Mr.  Debish Mukherjee",
        "providerDepartment": "Mechanical",
        "providerAdmissionYear": 1988,
        "providerPassingYear": 1992,
        "providerDetails": "Debish Mukherjee entered JGEC in the year 1988. Out of 2000 Selected students for Engineering in that year by the WBJEE Board he took admission in JGEC in that year and at that time there were only three branches.As per his ambition in life he took admission in Mechanical Engineering at JGEC leaving the other stream opportunity in other Engineering College at Calcutta. In college he served for lot of activities like College Sports Club participating in College Football Team and Cricket Team. He also participated on behalf of College for Jalpaiguri District League Cricket Tournament and Inter Engineering College Cricket Tournament. He was deeply involved in College Cultural/ Social fest. After graduation from JGEC in 1992, he served two organizations and from 1994 till date he is working with Larsen and Toubro in India and abroad at different positions and assignment.Besides his profession, he is also very fond of Cultural and Social activities. For giving this Scholarship, his family was with him from day one and they have given whole hearted support. This scholarship is in the name of his father Late Shree Debdas Mukherjee, who has left this world in 2017 leaving his family (wife, son & daughter). He had sacrificed almost his entire life for the comforts of the family members, as a result many of which people has become successful in their lives. He went through a lot of struggle and taught us how to handle single handedly those struggles/problems of the family during the difficult phases while having financial crisis of the family. He knew the value of money which was very important for becoming successful in life. His positive attitude, understanding and support to needy people was very much appreciated by others and he will live in all our hearts forever.",
        "imageUrl": "/uploads/scholarship/Mr.- Debish Mukherjee-1737617583425-Debish.png",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": true,
        "whocanApply": "Any students of JGEC (2nd year onwards).",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Amount of INR 25,000 to one student. ",
        "whentoApply": "Scholarship shall be offered usually during the Annual Alumni meet every year in the month of August.",
        "createdAt": "2025-01-23T07:33:03.430Z",
        "updatedAt": "2025-01-23T07:33:03.430Z",
        "__v": 0
    },
    {
        "_id": "67921b71983c91175bac76e4",
        "title": "SMILES 99 SCHOLARSHIP",
        "subtitle": "For Engineering Students from All the Batches (Years) of JGEC",
        "description": "SMILES 99 is a scholarship program set up by the JGEC 1999 batch to bring smiles in the faces of current students in JGEC like how our alma mater had us smiling in those magical 4 years that we spent together at the college.With this scholarship, the 1999 batch intends to help a few students who have financial hardships in completing their undergraduate courses. The recipients of this scholarship will be able to use this amount to pay for education and other expenses that they would incur in their stay while studying at JGEC.",
        "providerName": "JGEC 1999 Batch",
        "providerDepartment": "N/A",
        "providerAdmissionYear": 1999,
        "providerPassingYear": 2003,
        "providerDetails": "It was a very challenging time when we graduated in the year 1999. The economic recession was at a peak. There was a need for new skill sets to cope up with the changing professional world embraced with digitalization. But there were few positive signs as well due to globalization, the rapid expansion of information technology and morale-boosting victory at Kargil. We took the time as a challenge. With our sheer passion and inquisitiveness, we gradually started adopting ourselves with the highly expanding globalized world. At the same time, we always kept ourselves connected with our root. The friendship which we cherished during our golden four years at our beloved campus became stronger. JGEC experience helped us to keep ourselves distinct in the exceedingly competitive world. JGEC values taught us to be modest and honest in our all endeavour.Today, it is time to paying back to our beloved Alma Mater, JGEC.Smile 99 Scholarship is a humble effort to encourage our future generation to excel.",
        "imageUrl": "/uploads/scholarship/JGEC-1999 Batch-1737628529231-Smiles-99.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": true,
        "whocanApply": "Any JGEC student from any discipline, 3rd Semester onwards, who is performing well and needs monetary assistance to continue their engineering course",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Rs. 10,000 to five undergraduate engineering students of JGEC. (subject to fund availability)",
        "whentoApply": "Between notification date and application receipt cut off dates .",
        "createdAt": "2025-01-23T10:35:29.247Z",
        "updatedAt": "2025-01-23T10:35:29.247Z",
        "__v": 0
    },
    {
        "_id": "67921cf1983c91175bac76e6",
        "title": "Late Prabhakar De Memorial Scholarship",
        "subtitle": "For any 3rd Year Engineering Students Of JGEC",
        "description": "The scholarship Scheme is initiated by Mrs. Jhumur Dey, granddaughter of late Prabhakar De, to support financially challenged promising engineering students of JGEC who have faced financial hardship and wish to complete the undergraduate education with an approach to fulfil community responsibilities, such as social activity and/ or environment related activity etc. Even the activity related document they have to submit each year. The money of this scholarship is supposed to be used to pay tuition and other academic expenses associated with earning valuable graduation degree from our beloved college. This scholarship is a symbolic pay back to our beloved alma mater. Theme behind this scholarship is to portray the message Our responsibility as privileged human beings is to pay back for the opportunities we've received.",
        "providerName": "Mrs. Jhumur Dey ",
        "providerDepartment": "N/A",
        "providerAdmissionYear": 1996,
        "providerPassingYear": 2000,
        "providerDetails": "Late Prabhakar De was born in a farmers’ family, studied in Kuchiakol Radhaballav Institution (the second oldest school of Bankura district) and was the first matriculate from his village Chhatra-ara in the year 1933. Without any means for further study, he chose the profession of a Primary School Teacher with a salary of Rs. 5/- per month and eventually became head teacher of the school. Lovingly called Yadav Master in his area, he was an idealistic and passionate teacher. To help the poor and the illiterate, he single handedly started an adult literacy centre in his school premises in evening. For his sincerity and popularity, he was selected as Secretary of the local food board committee during the great Bengal famine in 1943. His credibility and trustworthiness was highly praised in the adjoining thanas and Bishnupur subdivision for his regular visits to all the villages and his efficient and impartial distribution of food grains to the poor people. Once he was elected in gram panchayat election. He tried to help everyone whoever approached him, irrespective of caste or religion.In his family life, he was progressive and tried to impart best possible education to his children within his financial ability. He had two granddaughters and his filial love was unbound. He never expressed the desire of a grandson when the social milieu was just the opposite. His love touches our heart even now whenever we remember him. His active and noble life came to an end in 1991. ",
        "imageUrl": "/uploads/scholarship/Mrs.-Jhumur Dey -1737628913733-Late-Prabhakar-De.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": false,
        "whocanApply": "Any 3rd year student of JGEC.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Amount of INR 20,000 to one student. ",
        "whentoApply": "Between notification date and application receipt cut off dates . ",
        "createdAt": "2025-01-23T10:41:53.736Z",
        "updatedAt": "2025-01-23T10:41:53.736Z",
        "__v": 0
    },
    {
        "_id": "679226e2983c91175bac76e8",
        "title": "Dr. R. P. Mandal & Mrs. P. Mandal endowed “JYOTI” SCHOLARSHIP",
        "subtitle": "For JGEC Engineering Students - 3rd Year",
        "description": "Jyoti Scholarship Program, set up to bring Jyoti (eternal light) in the life of the current students of JGEC helping them to make a more progressive advance towards that ray of hope with the positive stimulants like our alma maters who had us burning the flame of nostalgia through those unforgettable 4 years that we spent together at college.With this scholarship, we intend to extend our love and support to a needy student who is facing the hardship of life and need that little extra lift to push open the door to a bright future. The recipients of this scholarship will be able to use this amount to pay for education and other expenses that they would incur in their stay while studying at JGEC.",
        "providerName": "Rudranil Mandal",
        "providerDepartment": "N/A",
        "providerAdmissionYear": 0,
        "providerPassingYear": 0,
        "providerDetails": "Time and tide wait for No one. It may be hard even harder and might be hardest, but we have to fight back in this crucial pandemic situation and any other subsequent variant that may come by.The situation is and always will be difficult which indeed make us more human and despite the ever-evolving digitization and economical ups and down human life must go on. We have to be strong, need to be disciplined, nurtured to be honest and be steady like the Sun to keep ourselves adopting with these ever-changing globalized scenarios. At the same time, we need to keep ourselves connected to our root. The friendship that took root during our four golden formative years at our beloved campus became more cherished and stronger in the later years. JGEC experience helped us to keep ourselves distinct in the exceedingly competitive world. JGEC values taught us to be humble and honest in all our endeavour.Today, it is time to return back to our beloved Alma Mater, JGEC.Jyoti Scholarship is an effort to nurture our future generation to excel.",
        "imageUrl": "/uploads/scholarship/Rudranil-Mandal-1737631458867-Dr.png",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": false,
        "whocanApply": "JGEC student from any discipline, Pursuing 3rd Year, who is performing well and needs monetary assistance to continue their engineering course.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Rs. 10,000 to any undergraduate engineering students of JGEC.",
        "whentoApply": "Between notification date and application receipt cut off dates . ",
        "createdAt": "2025-01-23T11:24:18.878Z",
        "updatedAt": "2025-01-23T11:24:18.878Z",
        "__v": 0
    },
    {
        "_id": "6792284d983c91175bac76ea",
        "title": "KANTHA 96 Scholarship",
        "subtitle": "For Engineering Students from  2nd and 3rd (Years) of JGEC",
        "description": "KANTHA 96 is a scholarship program set up by the JGEC 1996 batch to bring smiles in the faces of current students in JGEC like how our alma mater had us smiling in those magical 4 years that we spent together at the college. With this scholarship, the 1996 batch intends to help two students who have financial hardships in completing their undergraduate courses. The recipients of this scholarship will be able to use this amount to pay for education and other expenses that they would incur in their stay while studying at JGEC.",
        "providerName": "JGEC Batch of 1996",
        "providerDepartment": "N/A",
        "providerAdmissionYear": 1992,
        "providerPassingYear": 1996,
        "providerDetails": "It was a very challenging time when we graduated in the year 1996. The economic recession was at a peak. There was a need for new skill sets to cope up with the changing professional world embraced with digitalization. But there were few positive signs as well due to globalization, and the rapid expansion of information technology. We took the time as a challenge. With our sheer passion and inquisitiveness, we gradually started adopting ourselves with the highly expanding globalized world. At the same time, we always kept ourselves connected with our root. The friendship which we cherished during our golden four years at our beloved campus became stronger. JGEC experience helped us to keep ourselves distinct in the exceedingly competitive world. JGEC values taught us to be modest and honest in our all endeavour.KANTHA 96 Scholarship is a humble effort to encourage our future generation to excel. Two of our batchmates have passed away few years ago. Name of the scholarship KANTHA 96 has been derived from their name KANAD & PARTHA.",
        "imageUrl": "/uploads/scholarship/JGEC-Batch of 1996-1737631821759-istockphoto-1332100919-612x612.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": false,
        "whocanApply": "Any JGEC student (one from 2nd year & one from 3rd year) from any discipline, 3rd Semester onwards, who is performing well and needs monetary assistance to continue their engineering course.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Rs. 10,000 each to two undergraduate engineering students of JGEC.",
        "whentoApply": "Between notification date and application receipt cut off dates . ",
        "createdAt": "2025-01-23T11:30:21.771Z",
        "updatedAt": "2025-01-23T11:30:21.771Z",
        "__v": 0
    },
    {
        "_id": "67922a08983c91175bac76ec",
        "title": "LATE DEBOPRASAD SEN MEMORIAL SCHOLARSHIP",
        "subtitle": "For any JGEC student from any discipline, 3rd Semester onwards",
        "description": "Our beloved institute's alumni have formed a forum called Student Scholarship Scheme,which is a wonderful attempt to help needy students. I feel both grateful and overwhelmed at the prospect of being a part of this community. JGEC has made a significant contribution in moulding me to fit into the industry in every way. Personally, I believe there is no better way to spend this modest bit of my hard-earned money. It gives me tremendous joy to make this tiny effort to repay our cherished alma institution.",
        "providerName": "Mr. Nabin Ghosh ",
        "providerDepartment": "Mechanical",
        "providerAdmissionYear": 1984,
        "providerPassingYear": 1988,
        "providerDetails": "This sponsorship is dedicated to our batch mate, Late Deboprasad Sen, whose life was cut short in an unpleasant Maskalai Bari tragedy in 1986, while we were 2nd year students.",
        "imageUrl": "/uploads/scholarship/Mr.-Nabin Ghosh -1737632264003-LATE DEBOPRASAD SEN MEMORIAL SCHOLARSHIP.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": true,
        "whocanApply": "Any JGEC student from any discipline, 3rd Semester onwards, who is performing well and needs monetary assistance to continue their engineering course.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Rs. 18,000 one engineering student of JGEC.",
        "whentoApply": "Between notification date and application receipt cut off dates . ",
        "createdAt": "2025-01-23T11:37:44.008Z",
        "updatedAt": "2025-01-23T11:37:44.008Z",
        "__v": 0
    },
    {
        "_id": "67922b63983c91175bac76ee",
        "title": "SMILES 99 SCHOLARSHIP",
        "subtitle": "For any JGEC student from any discipline, 3rd Semester onwards",
        "description": "SMILES 99 is a scholarship program set up by the JGEC 1999 batch to bring smiles in the faces of current students in JGEC like how our alma mater had us smiling in those magical 4 years that we spent together at the college.With this scholarship, the 1999 batch intends to help a few students who have financial hardships in completing their undergraduate courses. The recipients of this scholarship will be able to use this amount to pay for education and other expenses that they would incur in their stay while studying at JGEC.",
        "providerName": "JGEC Batch of 1999",
        "providerDepartment": "N/A",
        "providerAdmissionYear": 1995,
        "providerPassingYear": 1999,
        "providerDetails": "It was a very challenging time when we graduated in the year 1999. The economic recession was at a peak. There was a need for new skill sets to cope up with the changing professional world embraced with digitalization. But there were few positive signs as well due to globalization, the rapid expansion of information technology and morale-boosting victory at Kargil. We took the time as a challenge. With our sheer passion and inquisitiveness, we gradually started adopting ourselves with the highly expanding globalized world. At the same time, we always kept ourselves connected with our root. The friendship which we cherished during our golden four years at our beloved campus became stronger. JGEC experience helped us to keep ourselves distinct in the exceedingly competitive world. JGEC values taught us to be modest and honest in our all endeavour.Today, it is time to paying back to our beloved Alma Mater, JGEC. Smile 99 Scholarship is a humble effort to encourage our future generation to excel.",
        "imageUrl": "/uploads/scholarship/JGEC-Batch of 1999-1737632611834-Smiles-99.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": true,
        "whocanApply": "Any JGEC student from any discipline, 3rd Semester onwards, who is performing well and needs monetary assistance to continue their engineering course.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Rs. 10,000 to five undergraduate engineering students of JGEC. (subject to fund availability)",
        "whentoApply": "Between notification date and application receipt cut off dates . ",
        "createdAt": "2025-01-23T11:43:31.836Z",
        "updatedAt": "2025-01-23T11:43:31.836Z",
        "__v": 0
    },
    {
        "_id": "67922c28983c91175bac76f0",
        "title": "Smile 2004 Scholarship",
        "subtitle": "For any JGEC student from any discipline, 3rd Semester onwards",
        "description": "SMILE 2004 is a scholarship program set up by the JGEC 2004 batch to bring smiles in the faces of current students in JGEC like how our alma mater had us smiling in those magical 4 years that we spent together at the college.With this scholarship, the 2004 batch intends to help two students who have financial hardships in completing their undergraduate courses. The recipients of this scholarship will be able to use this amount to pay for education and other expenses that they would incur in their stay while studying at JGEC.",
        "providerName": "JGEC Batch of 2004",
        "providerDepartment": "N/A",
        "providerAdmissionYear": 2000,
        "providerPassingYear": 2004,
        "providerDetails": "It was a very challenging time when we graduated in the year 2004. The economic recession was at a peak. There was a need for new skill sets to cope up with the changing professional world embraced with digitalization. But there were few positive signs as well due to globalization, and the rapid expansion of information technology. We took the time as a challenge. With our sheer passion and inquisitiveness, we gradually started adopting ourselves with the highly expanding globalized world. At the same time, we always kept ourselves connected with our root. The friendship which we cherished during our golden four years at our beloved campus became stronger. JGEC experience helped us to keep ourselves distinct in the exceedingly competitive world. JGEC values taught us to be modest and honest in our all endeavour.Today, it is time to paying back to our beloved Alma Mater, JGEC. Smile 2004 Scholarship is a humble effort to encourage our future generation to excel.",
        "imageUrl": "/uploads/scholarship/JGEC-Batch of 2004-1737632808159-Smile 2004.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": true,
        "whocanApply": "Any JGEC student from any discipline, 3rd Semester onwards, who is performing well and needs monetary assistance to continue their engineering course.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Rs. 12,000 each to two undergraduate engineering students of JGEC.",
        "whentoApply": "Between notification date and application receipt cut off dates . ",
        "createdAt": "2025-01-23T11:46:48.162Z",
        "updatedAt": "2025-01-23T11:46:48.162Z",
        "__v": 0
    },
    {
        "_id": "67922d16983c91175bac76f2",
        "title": "Sri Sukhendu Bikas Goswami & Srimati Rani Goswami Memorial Scholarship",
        "subtitle": "For all the EE students of JGEC (any year).",
        "description": "The scholarship Scheme is initiated by Subir Goswami, to support financially challenged promising engineering students of JGEC who have faced financial hardship and wish to complete the undergraduate education with an approach to fulfil community responsibilities. The money of this scholarship is supposed to be used to pay tuition and other academic expenses associated with earning valuable graduation degree from our beloved college. This scholarship is a symbolic pay back to our beloved alma mater. Theme behind this scholarship is to portray the message Our responsibility as privileged human beings is to pay back for the opportunities we've received",
        "providerName": "Subir Goswami",
        "providerDepartment": "Electrical",
        "providerAdmissionYear": 1977,
        "providerPassingYear": 1981,
        "providerDetails": "My name is Subir Goswami.  My college record would show my middle name also. I was Subir Kumar Goswami till I decided to drop my middle name.I completed my High School from Sargachhi Ramakrishna Mission High School in the year of 1975.  Then, after a year studying Physics Honours, I entered Jalpaiguri Government Engineering College to study Electrical Engineering in the year of 1976.  Those days the engineering courses were designed to complete by 5 years. So, in 1981, I finished my college study.  Besides participating in cricket matches, I involved myself on creation of Students Health Home initiative.  I donated Blood as and when required. I was a member of Students Union.After leaving college I worked with Mahindra Engineering & Chemical Products, then Burn Standard, Howrah Works.  I left Burn to join Siemens India – Rourkela office. After working for 2 years I came back to Siemens Calcutta Office. I stayed and worked at this office for 10 more years before immigrating to Canada. While working at Calcutta I went and lived in West Germany for more than 2 years. In Canada the engineering profession is very strictly regulated. So, I became a Professional Engineer of Ontario, Canada.  I worked with Hatch Associates Ltd and then with Siemens Canada. After 6 and half years living in Canada I immigrated to Florida, United States. I have been living 20 years in Florida.  I have been working at Siemens USA and expect to work some more years.I am married and have a son and a daughter.  I went back to visit my college in the year of 2009.  I come to visit my ancestral home at Kolkata once in every 2 years.",
        "imageUrl": "/uploads/scholarship/Subir-Goswami-1737633046789-Sri Sukhendu Bikas Goswami & Srimati Rani Goswami Memorial Scholarship.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": true,
        "whocanApply": "All the EE students of JGEC (any year).",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Amount of INR 15,000 each to two students. ",
        "whentoApply": "Between notification date and application receipt cut off dates . ",
        "createdAt": "2025-01-23T11:50:46.802Z",
        "updatedAt": "2025-01-23T11:50:46.802Z",
        "__v": 0
    },
    {
        "_id": "67922dbd983c91175bac76f4",
        "title": "Late MINA BHADURY Memorial Scholarship",
        "subtitle": "For any 4th. Year Engineering Students Of JGEC",
        "description": "The scholarship Scheme is initiated by Mr. Tapas Kumar Bhadury, son of late Mina Bhadury, to support bright but financially challenged promising engineering students of JGEC who have faced financial hardship and wish to complete the undergraduate education with an approach to fulfil community responsibilities, such as social activity and/ or environment related activity etc. Even the activity related document they have to submit each year. The money of this scholarship is supposed to be used to pay tuition and other academic expenses associated with earning valuable graduation degree from our beloved college. This scholarship is a symbolic pay back to our beloved alma mater. Theme behind this scholarship is to portray the message Our responsibility as privileged human beings is to pay back for the opportunities we've received.",
        "providerName": "Tapas Kumar Bhadury",
        "providerDepartment": "Mechanical",
        "providerAdmissionYear": 1981,
        "providerPassingYear": 1985,
        "providerDetails": "Late Mina Bhadury was born in a renowned family, in Murshidabad (Kaladanga) & married with School head Teacher & renowned Anchal Pradhan Sri Samiron Kumar Bhadury of Nimtita, Murshidabad.  She was an idealistic and passionate lady. To help the poor and the illiterate, she single handedly started for free tuition in her village with the help of her husband who used to roam about all the houses in the evening to see whether students are studying. She stood like a pillar in helping her husband to look after the poor of the villages. She used to teach the mythological subjects to the villagers & her sincerity and popularity was known beyond the boundaries. Her husband could focus on his dual work as Head master of a school & as Panchayat Pradhan (for 28 years) as full family was looked after by her. No beggar irrespective of caste, creed, religion could go out of her house without having food which she used to supervise herself. She was very much progressive in thought & action & hence left no stone unturned to see that best education was imparted to her sons & daughter within their limit. Her love touches our heart even now whenever we remember her. Her active and noble life came to an end on 5th January, 2004. ",
        "imageUrl": "/uploads/scholarship/Tapas-Kumar Bhadury-1737633213326-Late MINA BHADURY Memorial Scholarship.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": true,
        "whocanApply": "Any 4th. year student of JGEC.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Amount of INR 10,000 to one student",
        "whentoApply": "Between notification date and application receipt cut off dates . ",
        "createdAt": "2025-01-23T11:53:33.330Z",
        "updatedAt": "2025-01-23T11:53:33.330Z",
        "__v": 0
    },
    {
        "_id": "67922edf983c91175bac76f6",
        "title": "Late Kiriti Ranjan Das Memorial Scholarship",
        "subtitle": "For 2nd Year Electrical Engineering Students Only",
        "description": "The scholarship Scheme is initiated by Tapan Das, to support financially challenged electrical engineering students of JGEC who have faced financial hardship and wish to complete the undergraduate education with an approach to fulfil community responsibilities. The money of this scholarship is supposed to be used to pay tuition and other academic expenses associated with earning valuable graduation degree from our beloved college. This scholarship is a symbolic pay back to our beloved alma mater. Theme behind this scholarship is to portray the message \"Our responsibility as privileged human beings is to pay back for the opportunities we've received\"",
        "providerName": "Tapan Das",
        "providerDepartment": "Electrical",
        "providerAdmissionYear": 1977,
        "providerPassingYear": 1981,
        "providerDetails": "I am Tapan Das,an alumnus of JGEC. I was also one of the students who was part of the last batch of the 11-years Higher Secondary Course and last 5-years Engineering course. I had joined ASP SAIL (Steel Authority of India Ltd.), Durgapur, and have retired from the same organization in 2019.My father, Late Kiriti Ranjan Das, had completed his schooling in Chittagong (erstwhile East Pakistan) and graduated from Chittagong Government College (then affiliated to Calcutta University). He was also an employee of DSP SAIL. He, along with my mother, were the architects in shaping the childhood and careers of their 3 off-springs, my elder sister, my late younger sister and me. My elder sister, Mrs. Chhanda Pathak (BIT MESRA - 1980) and I (JGEC – 1981) have followed in his footsteps by pursuing engineering.This scholarship, of Rs 15,000 per year, is intended to extend a helping hand to an aspiring Electrical Engineer in JGEC (Second Year) in his/her pursuit of higher studies post Higher Secondary education.",
        "imageUrl": "/uploads/scholarship/Tapan-Das-1737633503236-Late Kiriti Ranjan Das Memorial Scholarship.png",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": false,
        "fourthSem": false,
        "fifthSem": false,
        "whocanApply": "Second Year Electrical Engineering Students of JGEC ",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Total amount of INR 15,000 for one student only .",
        "whentoApply": "Between notification date and application receipt cut off dates . ",
        "createdAt": "2025-01-23T11:58:23.251Z",
        "updatedAt": "2025-01-23T11:58:23.251Z",
        "__v": 0
    },
    {
        "_id": "67922fc3983c91175bac76f8",
        "title": "SGraffito by Joluites@SG",
        "subtitle": "For any JGEC student from any discipline, 3rd Semester onwards.",
        "description": "When it comes to paying back to college, scholarships are the best form of financial aid. In order to inspire and support the students who encounter the problems such as inability to cope with the high standards of studying as well as difficulty in paying recurring expenses such as tuition fees, hostel & mess charges and accessing basic study needs, we the Joluites in Singapore decided to introduce and continue scholarships to the financially challenged, academically sounds and socially involved students irrespective of batch & stream. This is an honest & sincere effort and a token pay back to our place of graduation where spent our precious four years of life.SGraffito designed for moulding yourself by scratching your inner ability with a partial economic support by the Joluites in Singapore.",
        "providerName": "Alumnus of Singapore",
        "providerDepartment": "N/A",
        "providerAdmissionYear": 0,
        "providerPassingYear": 0,
        "providerDetails": "Under the mentorship of Partha Pratim Basu Da, we the below Joluites united for SGraffito:Partha Pratim Basu (1976), Soumen Mitra (1989), Indranil Chaudhury (1990), Arabinda Sain (1991), Nagendra Singh (1992), Bhaskar Dandapathak (1992), Gurudas Basu (1993), Sayan Mahalanobis (1995), Koushik Mondal\t(1997), Sunil Mandal (1999), Srimanta Banerjee (2004), Tushar Subhra Mondal (2004), Suparna Ganguly (2005), Akash Ranjan Mitra (2005), Eshita Majumder (2005), Santanu Samanta (2006) and Arnav Kundu (2006).This Scholarship is a humble effort to encourage our future generation to excel and a small gesture to help ease some financial burden for our current students and help them achieve their career aspirations.",
        "imageUrl": "/uploads/scholarship/Alumnus-of Singapore-1737633731577-istockphoto-1332100919-612x612.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": true,
        "fourthSem": true,
        "fifthSem": true,
        "whocanApply": "Any JGEC student from any discipline, 3rd Semester onwards, who is performing well and needs economic aid to continue their engineering course.",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Rs. 11,000/- each to 3 undergraduate engineering students of JGEC.",
        "whentoApply": "Between notification date and application receipt cut off dates . ",
        "createdAt": "2025-01-23T12:02:11.579Z",
        "updatedAt": "2025-01-23T12:02:11.579Z",
        "__v": 0
    },
    {
        "_id": "6792313d983c91175bac76fa",
        "title": "Shine95",
        "subtitle": "For any 2 students from electrical,civil and mechanical streams.",
        "description": "Shine95 scholarship is a humble effort of five alumni of Jalu’95 batch to provide some relief to a small number of students of JGEC who are facing financial hardship in continuing their studies.This is an effort of giving back to our esteemed institute in some way where from we have graduated years back. We understand that this small effort probably is not sufficient and matching to the requirement of funds by the needy students, but we have decided to start it now in a small way, with an effort to make it bigger in future.Though a large number of financial aids are available now a days, we think it is still difficult for some of the needy students to get the aid in the form of educational loan/assistance. This scholarship will be disbursed only to students, who are not getting sufficient financial assistance from any other sources and feeling hardship to continue their studies at JGEC.",
        "providerName": "Alumnus of Shine95",
        "providerDepartment": "N/A",
        "providerAdmissionYear": 0,
        "providerPassingYear": 0,
        "providerDetails": "Dipanjan Roychowdhury, Prasenjit Sarkar, Suvendra Chakraborti, Ranjoy Ghosh & Subhasish Dutta.",
        "imageUrl": "/uploads/scholarship/Alumnus-of Shine95-1737634109285-istockphoto-1332100919-612x612.jpg",
        "firstSem": true,
        "secondSem": true,
        "thirdSem": false,
        "fourthSem": false,
        "fifthSem": false,
        "whocanApply": "Steams eligible for this scholarship would be ME/EE/CE",
        "AgeCriteria": "Age criteria is not applicable for this scholarship",
        "amountdetails": "Value of the scholarship for each student would be Rs.41000 per year (ie total value of scholarship for 2 students would be Rs.82000 per year)",
        "whentoApply": "Between notification date and application receipt cut off dates . ",
        "createdAt": "2025-01-23T12:08:29.287Z",
        "updatedAt": "2025-01-23T12:08:29.287Z",
        "__v": 0
    }
];
